### ISSUE TITLE
Built-in file picker crashes on master when selecting an image

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#407] opened 2024-08-02 22:54 UTC
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lexical-sort-0.3.1/src/cmp.rs:106:21:
attempt to multiply with overflow
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_const::panic_const_mul_overflow
   3: lexical_sort::cmp::natural_lexical_cmp
   4: core::slice::<impl [T]>::sort_unstable_by::{{closure}}
   5: core::slice::sort::shared::smallsort::insert_tail
   6: core::slice::sort::shared::smallsort::small_sort_general
   7: core::slice::sort::unstable::quicksort::quicksort
   8: core::slice::sort::unstable::quicksort::quicksort
   9: core::slice::sort::unstable::quicksort::quicksort
  10: core::slice::sort::unstable::quicksort::quicksort
  11: oculante::scrubber::get_image_filenames_for_directory
  12: oculante::scrubber::Scrubber::new
  13: oculante::drawe
  14: <notan_winit::backend::WinitBackend as notan_app::backend::BackendSystem>::initialize::{{closure}}::{{closure}}
  15: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run
  16: winit::platform_impl::platform::EventLoop<T>::run
  17: winit::event_loop::EventLoop<T>::run
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: notan_app::builder::AppBuilder<S,B>::build
  20: oculante::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: queue 0x5d83e3e98320 destroyed while proxies still attached:
  wl_buffer#34 still attached
  wl_buffer#39 still attached
  wl_shm_pool#38 still attached
  xdg_wm_base#27 still attached
  wl_output#16 still attached
  wl_output#15 still attached
  xdg_activation_v1#14 still attached
  zwp_pointer_constraints_v1#13 still attached
  zwp_text_input_manager_v3#12 still attached
  zxdg_decoration_manager_v1#11 still attached
  zwp_relative_pointer_manager_v1#10 still attached
  wp_fractional_scale_manager_v1#9 still attached
  wp_viewporter#8 still attached
  wl_shm#7 still attached
  wl_subcompositor#6 still attached
  wl_compositor#5 still attached
  wl_seat#4 still attached
  wl_registry#2 still attached

**Comment by woelper** [comment] 2024-08-03 12:13
By built-in, you mean the egui dialog?

This looks like something in lexical-sort failed. I am not able to reproduce this, maybe this only happens with a specific set of files in a directory?

**Comment by Stoppedpuma** [comment] 2024-08-03 14:10
> This looks like something in lexical-sort failed. I am not able to reproduce this, maybe this only happens with a specific set of files in a directory?

Going to assume so. The weird thing here is it wasn't working in my home folder earlier but now is? Nothing has changed there. My downloads folder on the other hand causes this 100% of the time.

**Comment by Stoppedpuma** [comment] 2024-08-03 14:23
This seems to be an issue only with cargo run, a build works fine?

**Comment by woelper** [comment] 2024-09-15 20:17
I think that several methods (such as overflow checks) panic in debug mode, where release has a different behavior, for example wrapping around. I will close this because this happens in a different crate and very likely is not present in a release build.

**Closed by woelper** 2024-09-15 20:17 UTC
Labels: bug
