### ISSUE TITLE
different behaviour depending how I open it

### ISSUE THREAD

**Issue by pwouik** [woelper/oculante#186] opened 2023-05-02 22:03 UTC
when I run oculante via open with on an image, modified preferences aren't saved
when I open it from the console the toolbar is smaller
0.6.63 aur package kde

**Comment by woelper** [comment] 2023-05-03 08:11
Thanks! I'll look at this!
Would it be possible to provide screenshots to see the difference?

When you saying "open with" you are referring to associating it in your desktop environment and double clicking an image in your file manager?

**Comment by woelper** [comment] 2023-05-03 21:07
I could reproduce the "not saving preference" problem and found the cause. I don't know though what you mean by "the toolbar is smaller".

**Comment by pwouik** [comment] 2023-05-03 21:11
![image](https://user-images.githubusercontent.com/62726872/236050392-1cf3c513-0ad6-4013-84cf-2af135b28323.png)
![image](https://user-images.githubusercontent.com/62726872/236050574-8b35fcbf-1a07-4e7c-ade7-6a1ee3ada789.png)
second is opened via kde

**Comment by woelper** [comment] 2023-05-03 21:41
Me too! :) This is strange and not something I could reproduce (I am on PopOS/Gnome though). This could be related to HiDPI, do you have a high resolution display?

**Comment by woelper** [comment] 2023-05-03 21:44
One more thing: is only the menu bar larger or the whole ui (info panel etc)?

**Comment by pwouik** [comment] 2023-05-03 22:49
whole ui

**Comment by woelper** [comment] 2023-05-04 16:52
My guess is that your desktop environment is setting something. Can you try this build please?
[oculante.zip](https://github.com/woelper/oculante/files/11399650/oculante.zip)

**Comment by pwouik** [comment] 2023-05-04 22:51
same, double clicking the executable instead of the command line makes the toolbar large

**Comment by pwouik** [comment] 2023-05-05 00:15
it is affected by System Settings > Display and Monitor > Display Configuration > Global Scale, but it is already at 100 % and I cant make it smaller

**Comment by woelper** [comment] 2023-06-03 20:07
Sorry for the delay. I could not reproduce this in Gnome, Mac or Windows. I guess I might have to try this out in a VM. Are you using a specific distro I could try?

**Comment by pwouik** [comment] 2023-06-03 23:27
I'm on archlinux kde xorg

**Comment by woelper** [comment] 2023-06-04 19:58
Hi!
I installed Manjaro / KDE as I thought this was the closest to your setup without going through the whole Arch installation. Unfortunately the title bar remains the same size, no matter if I associate a file type with oculante or start it via the terminal. Unfortunately I am unable to reproduce the issue because of that.

**Comment by woelper** [comment] 2024-02-21 21:35
Closing as I can't reproduce. Please re-open if you have any suggestions.

**Closed by woelper** 2024-02-21 21:35 UTC
