### ISSUE TITLE
man this just happened when i installed it from cargo

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [woelper/oculante#26] opened 2022-05-19 00:16 UTC
`C:\Users\10\Pictures>oculante`
`Error: "required extension \"WGL_ARB_create_context_profile\" not found"`

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-19 00:21
i think that the problem it's my graphics card

**Comment by woelper** [comment] 2022-05-20 19:03
Are you able to run a binary from the releases tab?

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-21 16:32
> Are you able to run a binary from the releases tab?

i tried a release and the same happened

**Comment by woelper** [comment] 2022-05-21 17:03
I just pushed a new release with an upgrade of notan (the engine used) could you please try the latest one? Your graphics card needs to support OpenGL 3.3 I believe.

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-21 17:20
Which one of the releases have a opengl 3.1 support (i cant change the
graphics card cus im on a laptop)

**Comment by woelper** [comment] 2022-05-21 18:51
Please try this one:
https://github.com/woelper/oculante/releases/tag/0.5.25

I am sorry that the switch to a new engine caused this for you. I decided to go for a new UI and some more modern features which seem to require a higher OpenGL version.

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-21 19:44
Thanks, I'll check it out.

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-21 19:47
The thing keeps happening

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-22 17:05
So the same issue is happening with the release version for me so idk

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-22 17:05
Sorry for close it

**Comment by woelper** [comment] 2022-05-22 20:18
No worries.
Unfortunately, as I don't share your hardware configuration, the only thing I can suggest is that you keep going back in the releases and pick the one that works. I assume it did work at some point for you?

**Comment by soyDESKTOP68A2MRFT** [comment] 2022-05-23 00:56
No, it didn't worked and my setup is:
Intel core i5 2450m
4GB of ram
Intel hd graphics 3000

**Comment by woelper** [comment] 2022-08-21 09:27
I've tested on my super old laptop and can't reproduce. I do have an intel hd 4000 in it though I believe. Can you run any of the demos located at https://nazariglez.github.io/notan-web/ ?

**Comment by woelper** [comment] 2024-02-21 21:32
Closing and continuing in #247

**Closed by woelper** 2024-02-21 21:32 UTC
