### ISSUE TITLE
Support for `dng` image format

### ISSUE THREAD

**Issue by aaronleopold** [woelper/oculante#528] opened 2024-11-29 20:32 UTC
**Is your feature request related to a problem? Please describe.**

I have a lot of DNG files in my photography workflow and oculante currently renders them as low quality tiff images (I assume it is pulling some lower quality thumb, perhaps?)

**Describe the solution you'd like**

Add support for DNG files to be rendered at full resolution

**Additional context**

I took a cursory glance and found there is at least one dng-specific library that maybe fits the bill: https://crates.io/crates/dng (edit to add a link to [rawloader](https://docs.rs/rawloader/latest/rawloader/) too). I also recognize this is not necessarily a standard format for most folks, so no worries if it doesn't fit the scope of your project 🙂

**Comment by woelper** [comment] 2024-11-29 21:33
Thanks for the issue!

I've recently added mime type detection instead of relying on the extension. Maybe DNG is falsely detected as tiff. There should be full dng support using raw handling as far as I know. I'll look into this.

Could you be so kind and attach an image here I can try out?

**Comment by aaronleopold** [comment] 2024-11-29 22:13
Ah okay, gotcha! I've uploaded an example DNG image [here](https://wormhole.app/Qq4nJ#LXuOr7uk13X9cYTzCY4Epw). The link expires in 24 hours, let me know if you'd like any others. Thank you!

**Comment by woelper** [comment] 2024-11-30 13:28
It was as expected, the image was detected as tiff. However, your particular file fails to load with `quickraw`, the library I am using due to an Exif parsing error.

**Comment by aaronleopold** [comment] 2024-12-01 18:28
> However, your particular file fails to load with `quickraw`

Huh, interesting. Are you able to see which bit might be malformed in the exif?

**Comment by woelper** [comment] 2024-12-01 19:47
Unfortunately no. I would suggest we open up the issue directly with quickraw. If you want, I can do a minimal example, but we'd need an image to test it to be accessible. Do you have an image that can be checked in to an example repository?

**Comment by aaronleopold** [comment] 2024-12-04 15:37
Sorry for my delayed response! If you don't mind, you're more than welcome to use the same dng file I had previously sent for a repro/write-up. I can also try to create the issue sometime later this week(end) and link this one, if that would be easier

**Comment by woelper** [comment] 2024-12-09 20:21
Unfortunately I can't use your image as it exceeds github's 100MB limit. Would you be able to supply an image that is < 100MB which also does not work?

**Comment by aaronleopold** [comment] 2024-12-10 18:05
Hm. Let me see if I can force one out of my camera using crop mode. I'll get back to you after work

**Comment by aaronleopold** [comment] 2024-12-11 00:43
So I created a little repro app, but GitHub says it is too large (55MB, compressed). I'll wormhole it again, maybe the limit is different for an issue body? https://wormhole.app/b6KYK#OlHROjpMWFVx0QQ5oHuAmg

**Comment by woelper** [comment] 2024-12-12 16:14
Damn, sorry, the link expired. Sorry I missed this. Could you upload it again please?

**Comment by Stoppedpuma** [comment] 2024-12-23 19:46
@aaronleopold Sorry to bother you but are you able to reupload this? I'm trying to squeeze this into the next release.

**Comment by aaronleopold** [comment] 2024-12-23 19:49
Thanks for the ping! Sorry this slipped my radar, I didn't notice the original ask. Here you go: https://wormhole.app/jdoRm#LI-IecCyQ_sKe34-0TzcGg

**Comment by Stoppedpuma** [comment] 2024-12-23 20:09
Thanks a lot! There's a workaround which has been merged into master which might work for you, I'll discuss this further with woelper and try to reproduce locally on our ends, either way this should be fixed in 0.9.2 (the upcoming release).

**Comment by woelper** [comment] 2024-12-23 20:32
Thanks! Repo updated!

https://github.com/woelper/dng-load-error

**Comment by woelper** [comment] 2024-12-23 20:34
I'd be grateful if someone could report this upstream with `quickraw`, if not let me know and I'll do that!

**Closed by woelper** 2024-12-23 20:34 UTC
Labels: bug

**Comment by Stoppedpuma** [comment] 2024-12-23 20:47
> I'd be grateful if someone could report this upstream with `quickraw`, if not let me know and I'll do that!

I've reported this to quickraw.
