### ISSUE TITLE
Bottom status bar can't display some chars like ä 

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#159] opened 2023-03-24 12:20 UTC
Instead it displays `a` and a square box, and this happens for both forms ä and ä (one is `a`+combining `¨`, the other one is precomposed )

**Comment by woelper** [comment] 2023-04-05 17:12
Wow, that is odd. Thanks for adding this. I was under the impression that all the libraries I use were ready for international text, maybe something changed because I switched the font.

**Comment by woelper** [comment] 2023-04-05 17:16
Could you actually check again with the latest version?
I am not able to reproduce this locally. What OS are you using?


![image](https://user-images.githubusercontent.com/3613791/230155153-fc00cad0-c38c-4684-b5da-a5f169ca15f9.png)

(Not showing status bar, but the path in the upper left, which uses the same font)

**Comment by eugenesvk** [comment] 2023-04-05 20:08
Fails on both windows and a mac with the latest version 0.6.60 (using the info box as well)
this is from a mac
<img width="153" alt="oculet" src="https://user-images.githubusercontent.com/12956286/230197525-7d307417-6ae2-4f73-a740-69f6c048ee51.png">

**Comment by woelper** [comment] 2023-04-05 22:10
Thanks! I only checked on Linux. Very interesting this happens on other platforms. Great you found this.

**Comment by woelper** [comment] 2023-04-11 15:47
This should be fixed now. Apparently this was an issue with the monospace font. It will be in the next release, probably end of the week.

**Comment by eugenesvk** [comment] 2023-04-11 15:52
> issue with the monospace font

yeah, fonts want to breathe as well and don't like being forced in a box :)

**Comment by woelper** [comment] 2023-04-11 16:21
I have the same impression...

**Comment by woelper** [comment] 2023-04-12 14:02
This will be in `0.6.61`.

**Closed by woelper** 2023-04-12 14:02 UTC
