### ISSUE TITLE
Settings' order is randomized on quit

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#217] opened 2023-08-22 11:17 UTC
Mentioned it in https://github.com/woelper/oculante/issues/180, but this is a separate issue (and that one is closed).

Something in the deserialization seems to have chagned, and the settings file now seems to save with a random order of all the keybinds/settings, which makes it impractical to backup your config with a version control system

(on a Mac)

1. Open oculante
2. Open recent file
3. Quit (using a keyboard shortcut or the menu)
4. Watch how all the settings are now reordered (repeat 1–3, and the order changes)

**Comment by woelper** [comment] 2023-08-22 11:58
Thanks for opening this one, I'll look into it. Is it just the key bindings that are in random order? If so, I'll just swap out the data structure to an ordered map.

**Comment by eugenesvk** [comment] 2023-08-22 12:25
you're right, just the key bindings, the other settings preserve their order.

(whatever previous data structure you had before was nice as it was matching the order of some other tools like python json dumps, which made filtering for backup easier)

**Comment by woelper** [comment] 2023-08-22 13:12
I don't think I changed the data structure (at least not recently). I just think that for the key bindings it's a Hashmap which is unordered by design. The serialization library I use (serde) does with it what it wants, and that's why I think the order is not guaranteed. This will be easy to fix as it sounds.

**Comment by woelper** [comment] 2023-08-22 20:13
This is now fixed and tested. I'll do a patch release for you today.

**Closed by woelper** 2023-08-22 20:13 UTC
