### ISSUE TITLE
1:1 zoom is not 1:1

### ISSUE THREAD

**Issue by the8472** [woelper/oculante#228] opened 2023-09-20 14:11 UTC
oculante version: 0.7.5, via `cargo install`
OS: arch linux
Desktop: Xorg/i3wm

Opening any image appears to open it with some zoom (maybe 110%?) which leads to staircase artifacts on sharp lines. Selecting "View 1:1" in the menu does not rectify this.

**Comment by woelper** [comment] 2023-09-20 18:31
Thanks for the report!

In general, when opening an image, the following happens:
- If the image is too large to fit into the window, it will be scaled to fit the window.
- If the image is smaller than the window, it will keep a scale of 1.

Pressing `1` or selecting the menu entry you mentioned should display the image unscaled, so there may be a bug there. I recently updated notan, the framework/engine I use for drawing, so something may have gone wrong.

Do you use a high-dpi device? May I ask your monitor size and display resolution?

**Comment by woelper** [comment] 2023-09-20 18:45
I just tried to reproduce this (very unscientifically) with my system image viewer opening the same picture again, but it seems I am not able to reproduce this:
![image](https://github.com/woelper/oculante/assets/3613791/6566351c-49be-40d8-bd00-ac1cfaaae805)

**Comment by the8472** [comment] 2023-09-20 18:56
> Do you use a high-dpi device?

No.

> May I ask your monitor size and display resolution?

27", 2560x1440, no pixel scaling applied


![image](https://github.com/woelper/oculante/assets/1065730/46b73f80-bbc3-488f-b6b3-faf7e9af1f26)

left is oculante

**Comment by woelper** [comment] 2023-09-20 19:16
Thank you for attaching a screenshot. I wonder if this is related to the multi-monitor setup. Does this change in any way if you move Oculante to a different monitor/start it on a different monitor?

**Comment by the8472** [comment] 2023-09-20 19:22
Yeah, on the secondary monitors it works fine. It switches the scaling when I move it between monitors.

**Comment by woelper** [comment] 2023-10-19 19:03
Hmmm... I finally found time to dig out my old Dell 27 inch with `2560x1440`, opened images with both Oculante and the system image viewer and both look the same, on my main laptop and the 27 inch - so I am not able to reproduce this. I use PopOS though, so maybe there is a difference in our setup...

**Comment by the8472** [comment] 2023-10-19 19:17
The secondary monitors are also rotated, if that matters.

**Comment by woelper** [comment] 2023-10-19 19:42
Hmm, I rotated mine too and it did not make a difference sadly

**Comment by woelper** [comment] 2024-05-12 17:58
Hi! I am closing this since I can't reproduce it. If this still persists, please feel free to reopen this with detailed reproduction instructions, ideally some that can be made without specific hardware.

**Closed** 2024-05-12 17:58 UTC

**Comment by Netzwerk2** [comment] 2024-11-27 23:13
I could reproduce this issue (on X11) with 2 monitors.

![image](https://github.com/user-attachments/assets/d801a000-62e6-424e-b37a-df9777932291)

When I open oculante on my left monitor, 1:1 is actually 1:1. It also stays that way when I move oculante to the right monitor.
However, if I open oculante on my right monitor, the whole UI, including the image, is bigger than it should be (see the image). If I then move the window to my left screen, the UI and image scale to the correct size.

It seems like the issue is my monitors having different DPIs.
This is also visible in the logs.

Left monitor
```
[2024-11-27T22:58:50Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
```
Right monitor
```
[2024-11-27T23:03:54Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1.0833333333333333
```

It appears that the image is scaled with the DPI, while it shouldn't. It is strange however, that the UI size stays the same if I open if on my left monitor, but adapts if it's opened on my right monitor.

**Comment by Netzwerk2** [comment] 2024-11-27 23:42
You can easily reproduce it by setting `WINIT_X11_SCALE_FACTOR` to something like 1.5.
