### ISSUE TITLE
SVGs are displayed as rasterised

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#372] opened 2024-06-20 16:06 UTC
**Describe the bug**
I'm going to guess this was done for performance reasons and should probably be a toggle.

**To Reproduce**
1. Open SVG
2. Zoom in
3. Reproduced

**Expected behavior**
Option to render SVGs correctly

**Screenshots / sample files**
![image](https://github.com/woelper/oculante/assets/58333920/fc5f6462-1034-4aee-b9d0-d7b4689a45df)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Hyprland (Wayland compositor)

**Comment by woelper** [comment] 2024-06-20 19:17
This is not a bug but a feature. SVGs are rendered as a bitmap. This also allows them to be edited with filters. 

That said, a configurable quality could be set to control scaling / SVG resolution.

**Comment by woelper** [comment] 2024-06-21 18:33
Closing as won't fix. I am not going to make this a complete svg renderer. Please open a new issue if you want control over SVG rendering quality.

**Closed by woelper** 2024-06-21 18:33 UTC
