### ISSUE TITLE
Image displayed wrong compared to other applications

### ISSUE THREAD

**Issue by matteoscopel** [woelper/oculante#330] opened 2024-05-18 19:19 UTC
**Describe the bug**
I have a photo that is developed with Darktable and correctly tagged as sRGB. The image is not displayed correctly by Oculante, while Windows' Photos shows it correctly, exactly how it looks in Darktable (see screenshot 1).
Photos shows it exactly the same way it is on Darktable. The image is correctly tagged as sRGB, as from screenshot 2.

**Expected behavior**
Oculante should match the visualization of the photo with other applications.

**Screenshots / sample files**
![Screenshot 2024-05-18 210938](https://github.com/woelper/oculante/assets/18525423/ec24ba7a-a679-4319-b730-3175b66253ed)
![image](https://github.com/woelper/oculante/assets/18525423/0dd099df-0d22-4e73-adde-9726347e7b7e)
Sample file:
[sample.zip](https://github.com/woelper/oculante/files/15366555/sample.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.8.21

**Comment by woelper** [comment] 2024-05-18 19:26
Hi! Could this be a duplicate of https://github.com/woelper/oculante/issues/258 ?

**Comment by matteoscopel** [comment] 2024-05-18 21:15
Ah, most definitely. Sorry, I didn't see it!

**Comment by woelper** [comment] 2024-05-19 11:51
No worries. I've started working on it though, so there may be hope this is fixed some time. It is a complex topic though, and also the library I am using (lcms) seems to be a bit slow, so I don't know if I make this the default.

**Closed by woelper** 2024-05-19 11:51 UTC
