### ISSUE TITLE
Entering/Exiting fullscreen mode doesn't retain image position

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#95] opened 2022-12-19 06:17 UTC
For example, if it's centered in the default window, when entering the fullscreen mode, the image shifts to the left (it only maintains its size), though the offset from the left size is also not preserved, e.g., a picture under the `Info` element in regular mode shifts to under the `RGBA` UI element in fullscreen

**Comment by woelper** [comment] 2022-12-19 07:33
Would it be ok to reset the image view if toggling fullscreen?

**Comment by eugenesvk** [comment] 2022-12-19 07:44
Better not, retaining image zoom/position is the best option, especially when the user carefully adjust said zoom/position (this is important, for example, when you compare images in a viewer and flipping between them is the best method of finding differences).

**Comment by woelper** [comment] 2022-12-19 09:38
I've been thinking more, and to do it properly I think I'd need access to the exact window geometry - consider this example:
![image](https://user-images.githubusercontent.com/3613791/208394035-e6dd8806-c53f-437a-878d-44848544ffb9.png)

In these examples, it is not enough to know how big the windows is now vs. how big it was - it is also relevant which side was extended. I'll look if there is a more clever way than what I am doing right now, but I think in the meantime resetting the view might be the most user-friendly option.

**Comment by woelper** [comment] 2022-12-19 09:57
Just to make sure: Your dream scenario would be if the pixel under the cursor did not change and scale stays the same?

**Comment by eugenesvk** [comment] 2022-12-19 10:07
Yes, only the stuff AROUND the picture should change, the picture itself should not move/resize on entering/exiting fullscreen
There is a single key (still in the dream ;) as oculante doesn't yet have it) to center an image, so it's not an issue if you want to reset — just press one key!

**Comment by eugenesvk** [comment] 2022-12-19 10:23
You're right, it's just it bugged and sometimes shows a generic image icon placeholder instead of a reset image, so I kind of forgot about it :)

**Comment by woelper** [comment] 2022-12-19 17:34
> You're right, it's just it bugged and sometimes shows a generic image icon placeholder instead of a reset image, so I kind of forgot about it :)

Sorry, I don't understand - what is bugged and shows a generic icon placeholder? Can you elaborate and/or provide a screenshot?

On the fullscreen-and-back topic, I am almost there. I store the initial window geometry and calculate an offset. However, there is a small error, as I get the inner window size, minus borders and title bar. So going fullscreen and returning to window mode will not be 100% pixel perfect as I don't know the titlebar size. I can use a constant to further reduce the offset, but it will not be perfectly accurate as I see it. I _do_ hope it's way better than what we have now.

**Comment by woelper** [comment] 2022-12-19 18:25
Closing this as completed and released, if there is anything wrong with reset view either please comment or open another issue. Thanks for this suggestion, good as always ;)

**Comment by eugenesvk** [comment] 2022-12-19 18:26
The image gets replaced with the same-sized icon placeholder (e.g., instead of an A4 picture I get an A4-sized <img width="16" alt="ic" src="https://user-images.githubusercontent.com/12956286/208492625-939241d7-f14a-45e0-aae9-2f17fd30c6c0.png">)
But I can't reproduce it, so maybe it wasn't tied to the fullscreen? (could it be some other error with loading the image when you 

> I don't know the titlebar size

a. maybe make it a config so via experimentation I could find the size of the titlebar on my system to make it perfect?

b. Actually, I wanted to ask for a way to remove the titlebar completely so you could just enjoy the picture, no UI (similar to https://github.com/woelper/oculante/issues/43, but not sure if you meant the titlebar as well or just the toolbar). I know I can do that on Windows with Autohotkey (I also remove the resize border there since it's useless), but then it's not as great as having a native option as the titlebar still flashes on launch before it gets removed; and on a Mac it can only be done by the app itself (and the resize border can't be removed or you won't be able to resize the window)

**Comment by woelper** [comment] 2022-12-19 18:32
Love the idea of a), will do that!

By titlebar I was referring to the window title drawn by the OS. So you want both all UI gone and the titlebar? I think I may be able to do that, maybe with TAB and Shift-TAB or something...

**Comment by eugenesvk** [comment] 2022-12-19 18:35
I don't think its working :(
Here is the same screen area with the default launch screen (bottom left corner) and in fullscreen

<img width="529" alt="1" src="https://user-images.githubusercontent.com/12956286/208495758-daaf4def-7c8d-42b7-9326-4a2dc9193821.png">
<img width="529" alt="2" src="https://user-images.githubusercontent.com/12956286/208495765-ac035a5c-3710-4c92-be9a-b59c6ca5f753.png">

**Comment by eugenesvk** [comment] 2022-12-19 18:44
> By titlebar I was referring to the window title drawn by the OS. So you want both all UI gone and the titlebar? I think I may be able to do that, maybe with TAB and Shift-TAB or something...

Yes, exactly, the window titlebar and the window resize border
Although I'd like to disable it **before creating the window** or persist the <kbd>⇧</kbd><kbd>⭾</kbd> setting (the other UI I might enable/disable whenever needed, but the titlebar I'll never need as I don't use it for dragging nor do I use its buttons, and the file name I was hoping to get via a better customizable UI element that could be an overlay toggle not to shift the image position)

**Comment by woelper** [comment] 2022-12-19 21:01
> I don't think its working :( Here is the same screen area with the default launch screen (bottom left corner) and in fullscreen
> 
> <img alt="1" width="529" src="https://user-images.githubusercontent.com/12956286/208495758-daaf4def-7c8d-42b7-9326-4a2dc9193821.png">
> 
> <img alt="2" width="529" src="https://user-images.githubusercontent.com/12956286/208495765-ac035a5c-3710-4c92-be9a-b59c6ca5f753.png">

This is strange. on `0.6.34` (Mac/Linux tested just now) my mouse cursor remains over the exact same position in the image when entering/exiting fullscreen, no matter where the window was before, although there seems some offset if it is dragged onto an external monitor.

This is what I do:
- Open an image
- move the oculante window somewhere, like lower right corner
- resize window
- place the cursor over a distinct part of the image, so I have a reference point
- hit "f"
- window goes into fullscreen, my cursor is still over the reference point
- hit "f"
- window goes into windowed mode, cursor is still over reference point

**Comment by eugenesvk** [comment] 2022-12-20 05:59
It's the same issue on Windows: 

Resized the app window and moved it to the bottom right corner, just above the taskbar
<img width="466" alt="1" src="https://user-images.githubusercontent.com/12956286/208594575-cd704424-cd5a-4b7a-9f99-77da801806ff.PNG">

Pressed the fullscreen button — the image moved to the center of the screen
<img width="840" alt="2" src="https://user-images.githubusercontent.com/12956286/208594577-dd071868-04bb-4479-b676-a1954a317f1c.PNG">

**Comment by woelper** [comment] 2022-12-20 16:10
I can reproduce this on Windows. The reason it is not working is that I only get 0,0 back for the window position, which is wrong. I'll have to provide an example and file an upstream bug. On Mac it works for me though...

**Comment by woelper** [comment] 2022-12-30 18:33
This is tested on linux, mac and windows now and should work.

**Closed by woelper** 2022-12-30 18:33 UTC

**Comment by eugenesvk** [comment] 2023-01-02 09:47
There are still two issues with this:
  - vertical offset is not perfet (but that should be solved when you expose this as a setting and/or allow removing the titlebar)
  - the picture momentarily "jumps" to the bottom right/bottom left area

https://user-images.githubusercontent.com/12956286/210215300-a9af6889-9622-4c0e-b202-8127f497ae87.mov
