### ISSUE TITLE
native wayland support

### ISSUE THREAD

**Issue by luiswirth** [woelper/oculante#324] opened 2024-05-15 19:20 UTC
**Is your feature request related to a problem? Please describe.**
Currently on wayland oculante runs under xwayland, meaning that, when using fractional scaling,
the whole application is pixelated.

**Describe the solution you'd like**
I would like for oculante to natively run under wayland.
Winit (if you are using it) should have support for this.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by woelper** [comment] 2024-05-15 19:46
Hi, and thanks for the report!

Could you have a quick look at [this issue](https://github.com/woelper/oculante/issues/299) and see if it is related?

I am not a wayland user, but I was under the impression Oculante did work natively. Could you tell me how I find out if it is running under xwayland?

I am using `notan` under the hood, which uses `winit` - so I have one layer of indirection that might be massaged to work correctly.

**Comment by luiswirth** [comment] 2024-05-24 14:10
I don't think this is related to the issue you mentioned. Since in this issue, the reporter at least gets a wayland error. For me oculante doesn't event try to run natively on wayland.

I can easily tell that oculante is using xwayland inside my wayland session, because of
- this log message:
  ```
  [2024-05-24T13:53:43Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
  ```
- and using xorg-xeyes, I can see which windows send mouse events to xorg. xeyes usually can't track my mouse cursor, but when inside of the oculante window xeyes does track my cursor, proving that it's running under xwayland.

In order to find out if an application is running under xwayland, you need to be running some kind of wayland compositor of course. I'm not quite sure what's the easiest for you to test this.
It might be weston. Just run weston from the tty and you'll be inside of it. You should also be able to run weston inside of Xorg, by also just running it inside an existing Xorg session.

**Comment by Stoppedpuma** [comment] 2024-10-25 16:31
@luiswirth Are you still able to reproduce this? I'm unable to reproduce this on multiple machines, the compositors in my testing are Sway, Hyprland, and Cosmic. As you mentioned, this could just be an issue with weston?

**Comment by luiswirth** [comment] 2024-10-25 16:35
For me oculante is still running under xwayland on hyprland... I don't know why.

**Comment by Stoppedpuma** [comment] 2024-10-25 16:48
Odd, I believe there's an option to disable xwayland in Hyprland if you would like to test if that works? There's also [environment variables](https://wiki.hyprland.org/Configuring/Environment-variables/) you can try but I don't think this would help? Are you running an nvidia card by chance?

**Comment by Stoppedpuma** [comment] 2024-12-13 17:58
@luiswirth Can you see if this variable solves this for you?

`WINIT_UNIX_BACKEND=wayland`

**Comment by Stoppedpuma** [comment] 2024-12-23 20:25
I'm going to close this as can't reproduce, If someone else runs into this in the future and the above command doesn't work then please respond to this issue or open another one.

**Closed by Stoppedpuma** 2024-12-23 20:25 UTC
