### ISSUE TITLE
Few key binding bugs

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#88] opened 2022-12-12 14:08 UTC
- Fullscreen is unreliable, need to press <kbd>f</kbd> twice sometimes, but even that often doesn't work (especially on exitig the fullscreen mode, sometimes I have to tap <kbd>f</kbd><kbd>d</kbd><kbd>f</kbd>, wait, do it again, haven't managed to reliably enable/disable it)

- <kbd>+</kbd> (tried both <kbd>=</kbd> and <kbd>⇧</kbd><kbd>=</kbd>) doesn't work to zoom out, so I can only zoom any pic into a pixel ;)

**Comment by woelper** [comment] 2022-12-14 21:46
I could reproduce that. This seems to be exclusive to MacOS as far as I know.

**Comment by eugenesvk** [comment] 2022-12-16 06:05
> I could reproduce that. This seems to be exclusive to MacOS as far as I know.

also on Windows (the zooming bug, fullscreen seems to be ok)

**Comment by woelper** [comment] 2022-12-18 21:16
It seems to improve once the key is registered on release - this should fix the problem hopefully. Also zoom now works with "+" and "=" which works on mac now. For some reason KeyCode::Plus did not register. This will be in the next release.

**Closed by woelper** 2022-12-18 21:16 UTC
Labels: bug
