### ISSUE TITLE
When browsing pictures with left and right keys

### ISSUE THREAD

**Issue by jjcruz404** [woelper/oculante#514] opened 2024-11-14 22:37 UTC
When browsing using left and right keys on the keyboard or in the UI, it won't follow the folder sorting, it jumps randomly

**Comment by Stoppedpuma** [comment] 2024-11-15 12:19
I'm unable to reproduce this, are you seeing this behaviour on the latest release or a build? Also note that Oculante sorts 0-9 before a-z.

[order.webm](https://github.com/user-attachments/assets/ec1fba92-7273-4a8f-a6a3-43473257aaf8)

**Comment by woelper** [comment] 2024-12-09 20:14
I'll close this as it can't be reproduced. Please feel free to reopen if we have a way to reproduce, such as a zipped folder with files that are not loaded in the expected order.

**Closed by woelper** 2024-12-09 20:14 UTC
